
#ifndef SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_HALCALLBACKS_DIGITALIOCALLBACKS_H_
#define SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_HALCALLBACKS_DIGITALIOCALLBACKS_H_


#include "SnobotSim/ExportHelper.h"

namespace SnobotSim
{
    EXPORT_ void InitializeDigitalIOCallbacks();
    EXPORT_ void ResetDigitalIOCallbacks();
}  // namespace SnobotSim

#endif  // SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_HALCALLBACKS_DIGITALIOCALLBACKS_H_
