
#ifndef SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_HALCALLBACKS_PWMCALLBACKS_H_
#define SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_HALCALLBACKS_PWMCALLBACKS_H_


#include "SnobotSim/ExportHelper.h"

namespace SnobotSim
{
    EXPORT_ void InitializePwmCallbacks();
    EXPORT_ void ResetPwmCallbacks();
}  // namespace SnobotSim

#endif  // SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_HALCALLBACKS_PWMCALLBACKS_H_
