/*
 * ISpiWrapper.hpp
 *
 *  Created on: May 7, 2017
 *      Author: PJ
 */

#ifndef SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_SIMULATORCOMPONENTS_SPI_ISPIWRAPPER_H_
#define SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_SIMULATORCOMPONENTS_SPI_ISPIWRAPPER_H_

#include <stdint.h>

#include "SnobotSim/ExportHelper.h"

class ISpiWrapper
{
public:
};

class EXPORT_ NullSpiWrapper : public ISpiWrapper
{
};

#endif // SNOBOTSIM_SNOBOT_SIM_SRC_MAIN_NATIVE_INCLUDE_SNOBOTSIM_SIMULATORCOMPONENTS_SPI_ISPIWRAPPER_H_
